name: atma_paylas_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  adaptive_theme: ^3.3.0
  another_flutter_splash_screen: ^1.2.0
  auto_route: ^7.8.2
  auto_route_generator: ^7.3.1
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  easy_localization: ^3.0.2
  file_picker: ^6.0.0
  flutter:
    sdk: flutter
  flutter_bounceable: ^1.1.0
  flutter_chat_ui: ^1.6.9
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.20.3
  flutter_map: ^5.0.0
  flutter_multi_formatter: ^2.11.14
  flutter_native_splash: ^2.3.5
  flutter_screenutil: ^5.8.4
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  flutter_verification_code: ^1.1.7
  fluttertoast: ^8.2.4
  fpdart: ^1.1.0
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.3.8
  http: ^1.1.2
  image_picker: ^1.0.5
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.3+1
  json_serializable: ^6.7.1
  latlong2: ^0.9.0
  left_scroll_actions: ^2.1.2
  liquid_progress_indicator_v2: ^0.5.0
  mask_text_input_formatter: ^2.5.0
  open_filex: ^4.3.4
  package_info_plus: ^4.2.0
  pretty_dio_logger: ^1.3.1
  riverpod: ^2.3.7
  riverpod_lint: ^2.0.1
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  validatorless: ^1.2.3
  webview_flutter: ^4.4.1
  webview_flutter_android: ^3.12.0
  webview_flutter_wkwebview: ^3.9.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/bottomnavbar/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
