// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAa0ceKfa3k6GEabjdvOUuIBcAOtmBPaU',
    appId: '1:701886679203:web:cc6e44e5b5d5f9a5aad716',
    messagingSenderId: '701886679203',
    projectId: 'atmapaylas-412414',
    authDomain: 'atmapaylas-412414.firebaseapp.com',
    storageBucket: 'atmapaylas-412414.appspot.com',
    measurementId: 'G-STZ9NQB2YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmoqd9SRDJknVQZC981j4yRGdfdMVYjds',
    appId: '1:701886679203:android:60b5141f7a586cd2aad716',
    messagingSenderId: '701886679203',
    projectId: 'atmapaylas-412414',
    storageBucket: 'atmapaylas-412414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmk95656d0HnTX-Y3KDFpVqTuxHSo6vsk',
    appId: '1:701886679203:ios:367062ee57e62a8daad716',
    messagingSenderId: '701886679203',
    projectId: 'atmapaylas-412414',
    storageBucket: 'atmapaylas-412414.appspot.com',
    iosBundleId: 'com.atmapaylas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmk95656d0HnTX-Y3KDFpVqTuxHSo6vsk',
    appId: '1:701886679203:ios:009a48fbcee3acc6aad716',
    messagingSenderId: '701886679203',
    projectId: 'atmapaylas-412414',
    storageBucket: 'atmapaylas-412414.appspot.com',
    iosBundleId: 'com.example.atmaPaylasApp.RunnerTests',
  );
}
